package com.yusj.pangolin.jute.compiler;

import java.io.File;
import java.io.IOException;
import java.util.List;

/**
 * @Description
 * @Author kakalgy
 * @Date 2018/10/8 23:11
 **/
public class CSharpGenerator {
    private List<JRecord> mRecList;
    private final File outputDirectory;

    /**
     * Creates a new instance of CSharpGenerator
     *
     * @param name            possibly full pathname to the file
     * @param ilist           included files (as JFile)
     * @param rlist           List of records defined within this file
     * @param outputDirectory
     */
    CSharpGenerator(String name, List<JFile> ilist, List<JRecord> rlist,
                    File outputDirectory) {
        this.outputDirectory = outputDirectory;
        mRecList = rlist;
    }

    /**
     * Generate C# code. This method only creates the requested file(s)
     * and spits-out file-level elements (such as include statements etc.)
     * record-level code is generated by JRecord.
     */
    void genCode() throws IOException {
        for (JRecord rec : mRecList) {
            rec.genCsharpCode(outputDirectory);
        }
    }
}
